// Session keys
USER_TOOLTIP_KEY          = 'user-tooltip';
CURRENT_SEARCH_KEY        = 'current-search';
CURRENT_TAG_KEY           = 'current-tag';
CURRENT_COLLECTION_KEY    = 'current-collection';
HAS_BACK_ARROW_KEY        = 'has-back-arrow';
HIDE_SEARCH_BAR           = 'hide-search-bar';
SIDEBAR_OPEN_KEY          = 'sidebar-is-open';
SIDEBAR_ADDING_COLLECTION = 'sidebar-is-adding-collection';
MODAL_VISIBLE_KEY         = 'modal-is-visible';